### ISSUE TITLE
Cannot build on Debian / SteamOS

### ISSUE THREAD

**Issue by mdeguzis** [cflavio/yorg#7]
Hi, professorkaos64 from /r/linux_gaming here. Attempted a build using scons, with no luck. But snipped and log is below. What would help is, if you listed the packages or libraries needed for building, even if just "SDL 2".

```
make[1]: Entering directory '/build/yorg-0.6.0+git+bsos'
scons linux_64=1 images=1 lang=1 tracks=1
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: built
bld_images(["assets/images/icons/pinterest_png.png", "assets/images/icons/google_plus_png.png", "assets/images/icons/youtube_png.png", "assets/images/icons/tumblr_png.png", "assets/images/icons/facebook_png.png", "assets/images/icons/twitter_png.png", "assets/images/icons/feed_png.png", "assets/images/icon/icon16_png.png", "assets/images/icon/icon48_png.png", "assets/images/icon/icon32_png.png", "assets/images/icon/icon256_png.png", "assets/images/icon/icon128_png.png"], ["assets/images/icons/pinterest_png.psd", "assets/images/icons/google_plus_png.psd", "assets/images/icons/youtube_png.psd", "assets/images/icons/tumblr_png.psd", "assets/images/icons/facebook_png.psd", "assets/images/icons/twitter_png.psd", "assets/images/icons/feed_png.psd", "assets/images/icon/icon16_png.psd", "assets/images/icon/icon48_png.psd", "assets/images/icon/icon32_png.psd", "assets/images/icon/icon256_png.psd", "assets/images/icon/icon128_png.psd"])
scons: *** [assets/images/icons/pinterest_png.png] ValueError : invalid literal for int() with base 10: '1:'
Traceback (most recent call last):
  File "/usr/lib/scons/SCons/Action.py", line 1064, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/build/yorg-0.6.0+git+bsos/yyagl/build/imgs.py", line 6, in bld_images
    map(__bld_img, [str(src) for src in source])
  File "/build/yorg-0.6.0+git+bsos/yyagl/build/imgs.py", line 18, in __bld_img
    alpha, size = __img_alpha_size(fname)
  File "/build/yorg-0.6.0+git+bsos/yyagl/build/imgs.py", line 13, in __img_alpha_size
    return alpha, [int(dim) for dim in dim_split(geom)]
ValueError: invalid literal for int() with base 10: '1:'
scons: building terminated because of errors.
```

Log: http://sprunge.us/IZMX

**Comment by cflavio** [comment]
Hi mdeguzis! What is the output of the following command? Thanks!
identify -verbose "assets/images/icons/google_plus_png.png" | grep Geometry

PS Actually I've written a small list of prerequisites in the readme, I am going to add missing stuff as I find them.

**Comment by mdeguzis** [comment]
Hi. Inside the build chroot, this is the return value of that command

```
$ identify -verbose "assets/images/icons/google_plus_png.png" | grep Geometry
bash: identify: command not found

$ apt-get install -y imagemagick
$ identify -verbose "assets/images/icons/google_plus_png.png" | grep Geometry

identify: unable to open image `assets/images/icons/google_plus_png.png': No such file or directory @ error/blob.c/OpenBlob/2709.
identify: unable to open file `assets/images/icons/google_plus_png.png' @ error/png.c/ReadPNGImage/3922.

root@archboxmtd:/build/yorg-0.6.0+git+bsos# ls -la assets/images/icons/google_plus_png*
-rw-r--r-- 1 pbuilder pbuilder 6424 Jul  4 16:36 assets/images/icons/google_plus_png.psd
```

This got me farther.
```
sh: 1: egg2bam: not found
Traceback (most recent call last):
  File "yyagl/build/process_track.py", line 1, in <module>
    from panda3d.core import loadPrcFileData, BitMask32
ImportError: No module named panda3d.core
Traceback (most recent call last):
  File "yyagl/build/process_track.py", line 1, in <module>
    from panda3d.core import loadPrcFileData, BitMask32
ImportError: No module named panda3d.core
Traceback (most recent call last):
  File "yyagl/build/process_track.py", line 1, in <module>
    from panda3d.core import loadPrcFileData, BitMask32
ImportError: No module named panda3d.core
```

I am unsure what package provides this command/panda3D

**Comment by mdeguzis** [comment]
Looks like I may need to create a package for https://pypi.python.org/pypi/Panda3D. Please confirm this first. I have a script to help conver pypi packages to Debian packages.

**Comment by cflavio** [comment]
Yes, Panda3D is a prerequisite for building.

**Comment by mdeguzis** [comment]
I just about got the package for panda3d built. For whatever reason, they decided to use a custom python script instead of something standard like a Makefile...

After this I can do a formal build of Yorg :)

**Comment by cflavio** [comment]
Hi! I think that the reason is that, when they wrote that script, it didn't exist a cross-platform builder system. Anyway, they're porting it to CMake. ;)

**Comment by mdeguzis** [comment]
hahah watch them do that 2 weeks after I get this all built. Oh well, no problem, I almost have it anyway. Their debian files generation is strange, and doesn't add a source section, so I have to use sed to pipe in the section or just supply my own.
